export const ROUTES = Object.freeze({
  login: '/login',
  signup: '/signup',
  dashboard: '/dashboard',
  experience: '/experience',
  experienceWrite: '/experience/write',
  careerDecision: '/career-decision',
  careerAnalysis: '/career-analysis',
  resume: '/resume',
  coverLetters: '/cover-letters',
  coverLetterOther: '/cover-letters/other',
  coverLetterLibrary: '/cover-letters/library',
  successExamples: '/success-examples',
  successExamplesWorkspace: '/success-examples/workspace',
  speech: '/speech',
  interviewExamples: '/interview-examples',
  interviewWorkspace: '/interview-examples/workspace',
  careerInformation: '/career-information',
  careerInformationLibrary: '/career-information/library',
});
